graph TD
A[50,858 Admissions <br /> 38,638 Patients <br> &nbsp;&nbsp; Age > 16]
B[11,313 Admissions <br />10,139 Patients <br /> &nbsp;&nbsp;7,992 Arterial hypotension <br /> &nbsp;&nbsp;5,783 Vasopressor Use]
C[983 Admissions<br />  927 Patients<br />  &nbsp;&nbsp;948 Billing ICD Code of GI Bleeding<br /> &nbsp;&nbsp;359 Primary DRG of GI Bleeding]
D[800 Admissions<br />  763 Patients<br />  &nbsp;&nbsp; No Diagnosis of ESLD]
E[183 Admissions<br />  170 Patients<br />  &nbsp;&nbsp;Diagnosis of ESLD]

A --> B
B --> C
C --> D
C --> E